#!/usr/bin/env docker-compose -p atlassian -f

version: "3.2"

networks:
  internal:
    driver: overlay
    internal: true
  external:
    driver: overlay

volumes:
  data:
    driver: local
#     driver_opts:
#      type: nfs

services:

#  data:
#    restart: "no"
#    image: pvtmert/atlassian:data
#    build:
#      context: ./
#      dockerfile: data.dockerfile
#    volumes:
#      - type: volume
#        source: data
#        target: ./

  advisor:
    restart: always
    image: google/cadvisor
    networks:
      - external
    ports:
      - 8000:8080
    deploy:
      mode: global

  base:
    restart: on-failure
    image: pvtmert/atlassian:base
    build:
      context: ./
      dockerfile: base.dockerfile
    networks:
      - internal
      - external
    ports:
      - 80:80
    #volumes_from: data
    volumes: []
#      - ./nginx.conf:/etc/nginx/sites-enabled/default
#      - type: volume
#        source: data
#        target: /etc/nginx/sites-enabled
#        read_only: true
#        volume:
#          nocopy: true
#      - type: bind
#        source: ./
#        target: /data
#        read_only: true
#        volume:
#          nocopy: true
    depends_on:
      #- data
      - jira
      - crowd
      - bamboo
      - bitbucket
      - confluence

  jira:
    #command: [ "sleep", "999999999" ]
    restart: on-failure
    image: pvtmert/atlassian:jira
    build:
      context: ./
      dockerfile: jira.dockerfile
    networks:
      - internal
    #volumes_from: data
    volumes: []
      #- ./jira.server.xml:/data/conf/server.xml

  confluence:
    #command: [ "sleep", "999999999" ]
    restart: on-failure
    image: pvtmert/atlassian:confluence
    build:
      context: ./
      dockerfile: confluence.dockerfile
    networks:
      - internal
    #volumes_from: data
    volumes: []
      #- ./confluence.server.xml:/data/conf/server.xml

  bitbucket:
    #command: [ "sleep", "999999999" ]
    restart: on-failure
    image: pvtmert/atlassian:bitbucket
    build:
      context: ./
      dockerfile: bitbucket.dockerfile
    networks:
      - internal
    #volumes_from: data
    volumes: []

  bamboo:
    #command: [ "sleep", "999999999" ]
    restart: on-failure
    image: pvtmert/atlassian:bamboo
    build:
      context: ./
      dockerfile: bamboo.dockerfile
    networks:
      - internal
    #volumes_from: data
    volumes: []

  crowd:
    #command: [ "sleep", "999999999" ]
    restart: on-failure
    image: pvtmert/atlassian:crowd
    build:
      context: ./
      dockerfile: crowd.dockerfile
    networks:
      - internal
    #volumes_from: data
    volumes: []
